apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.deployment.namespace }}
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '8080'
spec:
  selector: 
    app: {{ .Values.deployment.appname }}   
  ports:
    - port: {{ .Values.network.port }}
      targetPort: {{ .Values.network.port }}
  type: LoadBalancer

  # spec:
  # selector: 
  #   app: jenkins-server
  # type: NodePort  
  # ports:
  #   - port: 8080
  #     targetPort: 8080
  #     nodePort: 32000

  # spec:
  # selector: 
  #   app: jenkins-server    
  # ports:
  #   - port: 8080
  #     targetPort: 8080
  # type: LoadBalancer