---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name:  {{ .Values.roles.role.name }}
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["*"]

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name:  {{ .Values.serviceaccount.name }}
  namespace: {{ .Values.deployment.namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name:  {{ .Values.roles.rolebinding.name }}
roleRef:
  apiGroup: {{ .Values.roles.rolebinding.apiGroup }}
  kind: ClusterRole
  name:  {{ .Values.roles.role.name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceaccount.name }}
  namespace: {{ .Values.deployment.namespace }}